# Generated by Django 5.1.15 on 2026-05-21 04:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source'], name='graph_edge_source_9b75b1_idx'), models.Index(fields=['target'], name='graph_edge_target_0b630e_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='uq_edge_source_target'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='chk_edge_no_self_loop')],
            },
        ),
    ]
